### PR TITLE
Restore generic, eq, ord, and show instances

### PR DESCRIPTION
**Pull request by jvliwanag**

### CODE REVIEW

**Comment by srghma** [comment]
You should run sync-cst-declaration-to-smart-cst.sh

**Comment by srghma** [comment]
And here is how to fix tests https://github.com/purescript-spec/purescript-spec/pull/109#issuecomment-714548316

**Comment by jvliwanag** [comment]
@srghma looks like the error on the build is caused by the override of purescript-either from packages.dhall. In particular, `Data.String.Regex.Unsafe` and `Test.Spec.Reporter.Tap` depend on the original fromLeft/fromRight definitions.

Removing that override fixes the build for me. Would it be alright to remove the override?

**Comment by srghma** [comment]
yes, we can do this too, I hope we don't use `import Either ((\/))`

**Comment by srghma** [comment]
thank you

**Pull request merged**
