### PR TITLE
Add test case for multiline type op

### PR DESCRIPTION
**Pull request by jvliwanag**
Added a test case for multiline type arrow / op

Currently though, it renders as:

```
type Foo = (FooBarBaz
            QuxQuuxQuz -> FooBarBaz
                          QuxQuuxQuz -> FooBarBaz
                                        QuxQuuxQuz -> FooBarBaz
                                                      QuxQuuxQuz)
```

How do we wish to format this? I can work on it once we've decided on a path

I'm leaning towards:

```
type Foo = ( FooBarBaz QuxQuuxQuz
             -> FooBarBaz QuxQuuxQuz
             -> FooBarBaz QuxQuuxQuz
             -> FooBarBaz QuxQuuxQuz
           )
```

Or perhaps we can even remove the parenthesis?

### CODE REVIEW

**Comment by flip111** [comment]
Proposal looks good to me. By hand i would format it like this usually

```haskell
type Foo = FooBarBaz QuxQuuxQuz -> FooBarBaz QuxQuuxQuz -> FooBarBaz QuxQuuxQuz -> FooBarBaz QuxQuuxQuz

type Foo
   = FooBarBaz QuxQuuxQuz
  -> FooBarBaz QuxQuuxQuz
  -> FooBarBaz QuxQuuxQuz
  -> FooBarBaz QuxQuuxQuz
```

**Comment by jvliwanag** [comment]
Closing this for now, since the pull request has grown in coverage.

**Comment by srghma** [comment]
looks super awesome, when we will be able to merge this ?)

**Comment by srghma** [comment]
i think: if tests are not failing - any time :wink:

**Comment by jvliwanag** [comment]
Opened #24 in favor of this 😅

**Pull request closed without merging**
