### PR TITLE
Update printing style

### PR DESCRIPTION
**Pull request by jvliwanag**
I wanted to take care of #22 and ended up changing  a number of things. This is my first usage of a pretty printer lib, so not entirely sure if I'm doing these right. The changes include the ff:

* Change printers to add newline prior to symbols. Favor indent over alignCurrentColumn.

```purescript
-- old
newtype Foo = Foo
              ( rowField :: Number
              , rowField2 :: Number
              | MyExtension + MyOtherExtension {someField :: Number}
              )

-- new
newtype Foo
  = Foo
    ( rowField :: Number
    , rowField2 :: Number
    | MyExtension + MyOtherExtension {someField :: Number}
    )
```

* Remove unneeded parenthesis on type declaration

```purescript
-- old
type Foo = (Foo A <+> Foo B)

-- new
type Foo = Foo A <+> Foo B
```

* Remove space after record/row parenthesis if within a line.

```purescript
-- old
newtype Foo = Foo (Array { foo :: Number })

-- new
newtype Foo = Foo (Array {foo :: Number})
```

* Remove space prior dot on forall

```purescript
-- old
newtype Foo = Foo (forall f . Functor f => f ~> Maybe)

-- new
newtype Foo = Foo (forall f. Functor f => f ~> Maybe)
```

* Fix breaking on TypeApp

```purescript
-- old
type Foo = (FooBarBaz
            QuxQuuxQuz -> FooBarBaz
                          QuxQuuxQuz -> FooBarBaz
                                        QuxQuuxQuz -> FooBarBaz
                                                      QuxQuuxQuz)

-- new
type Foo
  = FooBarBaz QuxQuuxQuz
  -> FooBarBaz QuxQuuxQuz
  -> FooBarBaz QuxQuuxQuz
  -> FooBarBaz QuxQuuxQuz
```

* Generalize printing of type, newtype and data declarations. Reuse TypeApp printing

--

I realize I may have take too much of a liberty changing up the printers a bit too much. If it is preferred that I take a step by step approach and a bit more bite sized series of pull requests, please let me know.

There are a number of missing parts I've left unsolved for now, since this one has already grown too big. But can help out on future pull requests including:
* ado, do statements
* constraint list in instance head

I'm also open to changing the printing styles of course.

### CODE REVIEW

**Comment by srghma** [comment]
re 

> Remove space after record/row parenthesis if within a line.
> -- old
> newtype Foo = Foo (Array { foo :: Number })
> 
> -- new
> newtype Foo = Foo (Array {foo :: Number})


purty always adds spaces

```
f :: Array { x :: Int, y :: Boolean }
f =
  [ { x: 1
    , y:
      true
    }
  , { x: 10, y: false }
  , { x: 0
    , y: true
    }
  ]
```

**Comment by srghma** [comment]
I too prefer

`{ foo :: Number }`

to

`{foo :: Number}`

because it's easier to go from `{ foo :: Number }`

to

```
{ foo :: Number
, bar :: ASDF
}
```

**Comment by srghma** [comment]
https://gitlab.com/joneshf/purty/-/blob/master/test/golden/files/formatted/Array.purs

**Comment by jvliwanag** [comment]
In line with that, would we prefer purty style of putting the operators at the end?

```purescript
foo ::
  forall a.
  Foo a =>
  a ->
  Int
```

It will make things much simpler. But not sure if that's the preferred style. Can of course be a sep pull request.

In the meantime, I'll change the space for records / rows.

**Comment by srghma** [comment]
> In line with that, would we prefer purty style of putting the operators at the end?
> 
> ```purescript
> foo ::
>   forall a.
>   Foo a =>
>   a ->
>   Int
> ```
> 
> It will make things much simpler. But not sure if that's the preferred style. Can of course be a sep pull request.
> 
> In the meantime, I'll change the space for records / rows.

I have no preference

purty author is using the `right styling` (you provided) in haskell, I use the `left styling`

added https://gitlab.com/joneshf/purty/-/issues/222

**Comment by jvliwanag** [comment]
I’ve reverted the spacing on rows on the last commit

**Pull request merged**
